const LESSONS = [
  {
    id: 1,
    title: "I Love Bands and Music",
    subtitle: "Lesson 1 - New Words",
    wordCount: 22,
    vocab: [
      { word: "all the time", korean: "내내, 아주 자주", eng_def: "at all times; continuously or very often", example: "He forgets his homework all the time.", audio: "all_the_time.wav", def_audio: "def_all_the_time.wav" },
      { word: "band", korean: "n. 밴드", eng_def: "a group of musicians who play music together", example: "Ben plays the guitar in a rock band.", audio: "band.wav", def_audio: "def_band.wav" },
      { word: "by one's side", korean: "좌우에, 옆에", eng_def: "close or beside someone", example: "She keeps a family photo by her side at work.", audio: "by_one_s_side.wav", def_audio: "def_by_one_s_side.wav" },
      { word: "each", korean: "a. 각각의", eng_def: "every one of two or more things or people", example: "The teacher always gives candies to each student.", audio: "each.wav", def_audio: "def_each.wav" },
      { word: "even", korean: "ad. ~도, 심지어", eng_def: "used to show that something is surprising", example: "He even goes to home with me.", audio: "even.wav", def_audio: "def_even.wav" },
      { word: "guide", korean: "n. 안내인", eng_def: "a person who shows the way and often gives information", example: "The guide leads us through the forest.", audio: "guide.wav", def_audio: "def_guide.wav" },
      { word: "gym", korean: "n. 체육관", eng_def: "a building or room that has equipment for doing physical exercises", example: "Tim goes to the gym every day.", audio: "gym.wav", def_audio: "def_gym.wav" },
      { word: "hearing", korean: "n. 청각", eng_def: "the ability to hear", example: "Loud music is not good for your hearing.", audio: "hearing.wav", def_audio: "def_hearing.wav" },
      { word: "keyboard", korean: "n. 키보드", eng_def: "a musical instrument with keys like a piano", example: "She carries her own keyboard for the concert.", audio: "keyboard.wav", def_audio: "def_keyboard.wav" },
      { word: "laugh", korean: "v. 웃다", eng_def: "to make a sound with your voice because you think something is funny", example: "She laughs at my funny story.", audio: "laugh.wav", def_audio: "def_laugh.wav" },
      { word: "magic", korean: "n. 마술", eng_def: "the use of tricks to entertain people", example: "My brother loves magic shows.", audio: "magic.wav", def_audio: "def_magic.wav" },
      { word: "match", korean: "v. 연결시키다", eng_def: "to put two things together in a suitable way", example: "Match the words with the pictures.", audio: "match.wav", def_audio: "def_match.wav" },
      { word: "memo", korean: "n. 메모", eng_def: "a usually brief written message from someone", example: "Mom leaves a daily memo for me.", audio: "memo.wav", def_audio: "def_memo.wav" },
      { word: "neighbor", korean: "n. 이웃", eng_def: "someone who lives near you", example: "My neighbor has two dogs.", audio: "neighbor.wav", def_audio: "def_neighbor.wav" },
      { word: "nod", korean: "v. 끄덕이다", eng_def: "to move the head down and then up again quickly", example: "He often nods his head along to music.", audio: "nod.wav", def_audio: "def_nod.wav" },
      { word: "person", korean: "n. 사람, 개인", eng_def: "a man, woman, or child", example: "The person with the hat is my cousin James.", audio: "person.wav", def_audio: "def_person.wav" },
      { word: "pop", korean: "a. 팝 (음악)의", eng_def: "of or relating to popular music", example: "I love pop songs a lot.", audio: "pop.wav", def_audio: "def_pop.wav" },
      { word: "practice", korean: "v. 연습하다 / n. 연습", eng_def: "to do something regularly so that you can do it better", example: "Grace practices the piano every day.", audio: "practice.wav", def_audio: "def_practice.wav" },
      { word: "special", korean: "a. 특별한", eng_def: "different from ordinary things and better in some way", example: "The restaurant has a special menu for children.", audio: "special.wav", def_audio: "def_special.wav" },
      { word: "subject", korean: "n. 과목", eng_def: "an area of knowledge or study, especially one that you study at school", example: "History is my favorite subject.", audio: "subject.wav", def_audio: "def_subject.wav" },
      { word: "tulip", korean: "n. 튤립", eng_def: "a large, bright flower that is shaped like a cup", example: "His garden is full of beautiful tulips.", audio: "tulip.wav", def_audio: "def_tulip.wav" },
      { word: "wide", korean: "a. 넓은", eng_def: "with a great distance from side to side; large", example: "There is a wide table in the kitchen.", audio: "wide.wav", def_audio: "def_wide.wav" }
    ]
  },
  {
    id: 2,
    title: "Healthy Food Fair",
    subtitle: "Lesson 2 - New Words",
    wordCount: 29,
    vocab: [
      { word: "bowl", korean: "n. 그릇", eng_def: "a round, deep dish used for food", example: "The bowl has some soup in it.", audio: "bowl.wav", def_audio: "def_bowl.wav" },
      { word: "chef", korean: "n. 요리사", eng_def: "a person who prepares food for people to eat; cook", example: "My uncle is a famous chef in my country.", audio: "chef.wav", def_audio: "def_chef.wav" },
      { word: "cherry tomato", korean: "n. 방울토마토", eng_def: "a type of very small tomato", example: "I like pasta with cherry tomatoes and basil leaves.", audio: "cherry_tomato.wav", def_audio: "def_cherry_tomato.wav" },
      { word: "different", korean: "a. 다른", eng_def: "not the same as something", example: "My brother and I like different kinds of music.", audio: "different.wav", def_audio: "def_different.wav" },
      { word: "enjoy", korean: "v. 즐기다", eng_def: "to like doing something", example: "He enjoys playing soccer with his friends.", audio: "enjoy.wav", def_audio: "def_enjoy.wav" },
      { word: "fair", korean: "n. 박람회", eng_def: "an event at which people show or sell things", example: "Many artists from different countries join the art fair.", audio: "fair.wav", def_audio: "def_fair.wav" },
      { word: "flour", korean: "n. 밀가루", eng_def: "a powder used for making bread and cakes", example: "You need flour, milk, and eggs for pancakes.", audio: "flour.wav", def_audio: "def_flour.wav" },
      { word: "fry", korean: "v. 튀기다", eng_def: "to cook food in hot oil", example: "We will fry some potatoes for dinner.", audio: "fry.wav", def_audio: "def_fry.wav" },
      { word: "garlic", korean: "n. 마늘", eng_def: "a small plant like an onion, used to give a strong taste to food", example: "This pasta uses only garlic and olive oil.", audio: "garlic.wav", def_audio: "def_garlic.wav" },
      { word: "healthy", korean: "a. 건강한", eng_def: "physically good and strong", example: "Regular exercise is a key to a healthy body.", audio: "healthy.wav", def_audio: "def_healthy.wav" },
      { word: "honey", korean: "n. 꿀", eng_def: "a sweet sticky, yellow substance made by bees", example: "Add honey for a tasty pizza.", audio: "honey.wav", def_audio: "def_honey.wav" },
      { word: "host", korean: "n. 진행자", eng_def: "a person who introduces guests and performers, especially on a television or radio show", example: "The host of the show has a great sense of humor.", audio: "host.wav", def_audio: "def_host.wav" },
      { word: "important", korean: "a. 중요한", eng_def: "having great meaning", example: "Regular exercise is important for your health.", audio: "important.wav", def_audio: "def_important.wav" },
      { word: "instead", korean: "ad. 대신에", eng_def: "in place of someone or something else", example: "I will wear a coat instead of a jacket today.", audio: "instead.wav", def_audio: "def_instead.wav" },
      { word: "jog", korean: "v. 조깅하다", eng_def: "to run at a slow steady speed for exercise", example: "Every morning, she jogs at the park.", audio: "jog.wav", def_audio: "def_jog.wav" },
      { word: "leaf", korean: "n. 잎", eng_def: "a flat and usually green part of a plant that grows out from a stem", example: "This is a leaf from that tree.", audio: "leaf.wav", def_audio: "def_leaf.wav" },
      { word: "nut", korean: "n. 견과류", eng_def: "a dry seed or fruit that has a hard shell", example: "Jenny enjoys a salad with a mix of nuts and vegetables.", audio: "nut.wav", def_audio: "def_nut.wav" },
      { word: "prize", korean: "n. 상", eng_def: "something given as a reward to the winner of a competition", example: "She always wins first prize in a speech contest.", audio: "prize.wav", def_audio: "def_prize.wav" },
      { word: "real", korean: "a. 진짜의", eng_def: "true, not fake or imaginary", example: "Is this ring real gold?", audio: "real.wav", def_audio: "def_real.wav" },
      { word: "regularly", korean: "ad. 규칙적으로", eng_def: "at the same time every day, week, month, etc. and usually often", example: "Maya regularly goes fishing with her dad.", audio: "regularly.wav", def_audio: "def_regularly.wav" },
      { word: "ride", korean: "v. 타다", eng_def: "to sit on a bicycle, motorcycle, or horse and make it move forward", example: "We will ride the train to the city.", audio: "ride.wav", def_audio: "def_ride.wav" },
      { word: "sentence", korean: "n. 문장", eng_def: "a group of words that makes a statement or asks a question", example: "Write a sentence about your favorite animal.", audio: "sentence.wav", def_audio: "def_sentence.wav" },
      { word: "skewer", korean: "n. 꼬치, 꼬챙이", eng_def: "a thin piece of wood or metal", example: "I want to eat chicken on skewers.", audio: "skewer.wav", def_audio: "def_skewer.wav" },
      { word: "soon", korean: "ad. 곧", eng_def: "in or within a short time; before long", example: "Dinner will be ready soon.", audio: "soon.wav", def_audio: "def_soon.wav" },
      { word: "teen", korean: "n. 10대 / a. 10대의", eng_def: "a young person between 13 and 19 years old", example: "Tony always carries his phone around, like most teens.", audio: "teen.wav", def_audio: "def_teen.wav" },
      { word: "thick", korean: "a. 걸쭉한", eng_def: "(of a liquid) not flowing easily", example: "The pasta sauce is thick and rich.", audio: "thick.wav", def_audio: "def_thick.wav" },
      { word: "topic", korean: "n. 주제", eng_def: "someone or something that people talk or write about", example: "You can choose a topic for your history project.", audio: "topic.wav", def_audio: "def_topic.wav" },
      { word: "trash", korean: "n. 쓰레기", eng_def: "things that you do not want and throw away", example: "He is throwing away the trash in the park.", audio: "trash.wav", def_audio: "def_trash.wav" },
      { word: "unhealthy", korean: "a. 건강하지 않은", eng_def: "not strong or well", example: "I won't eat unhealthy food like hamburgers often.", audio: "unhealthy.wav", def_audio: "def_unhealthy.wav" }
    ]
  },
  {
    id: 3,
    title: "Let's Be Positive",
    subtitle: "Lesson 3 - New Words",
    wordCount: 26,
    vocab: [
      { word: "angry", korean: "a. 화가 난", eng_def: "a. having strong feelings about something that you dislike very much", example: "She looks angry at my mistake.", audio: "angry.wav", def_audio: "def_angry.wav" },
      { word: "attitude", korean: "n. 태도", eng_def: "n. the way you think or feel about something", example: "I like her friendly attitude.", audio: "attitude.wav", def_audio: "def_attitude.wav" },
      { word: "be proud of", korean: "~을 자랑으로 여기다", eng_def: "to feel pleased about something good that you have or have done", example: "My grandparents are proud of me.", audio: "be_proud_of.wav", def_audio: "def_be_proud_of.wav" },
      { word: "cheer", korean: "v. 응원하다", eng_def: "v. to encourage somebody or to give them hope or comfort", example: "He gave me some flowers and cheered me up.", audio: "cheer.wav", def_audio: "def_cheer.wav" },
      { word: "contest", korean: "n. 대회", eng_def: "n. a competition or game in which people try to win", example: "They won first place in the dance contest.", audio: "contest.wav", def_audio: "def_contest.wav" },
      { word: "empty", korean: "a. 비어 있는 / v. 비우다", eng_def: "a. having nothing inside / v. to remove everything from inside something", example: "After the party, the plates were empty.", audio: "empty.wav", def_audio: "def_empty.wav" },
      { word: "famous", korean: "a. 유명한", eng_def: "a. known by very many or most people", example: "France is famous for its great food.", audio: "famous.wav", def_audio: "def_famous.wav" },
      { word: "fault", korean: "n. 잘못", eng_def: "n. responsibility for a problem, mistake, bad situation, etc.", example: "She was late for school, but it wasn't her fault.", audio: "fault.wav", def_audio: "def_fault.wav" },
      { word: "fried", korean: "a. 튀긴", eng_def: "a. cooked in hot oil", example: "Fried food always tastes good.", audio: "fried.wav", def_audio: "def_fried.wav" },
      { word: "happen", korean: "v. 일어나다", eng_def: "v. to take place, especially without being planned", example: "What will happen next?", audio: "happen.wav", def_audio: "def_happen.wav" },
      { word: "interested", korean: "a. 관심이 있는", eng_def: "a. wanting to know more", example: "He is interested in the reading club.", audio: "interested.wav", def_audio: "def_interested.wav" },
      { word: "lose", korean: "v. 잃어버리다, (경기에) 지다", eng_def: "v. to not be able to find something; to fail to succeed in a game, competition, etc.", example: "He lost his cell phone at the park.", audio: "lose.wav", def_audio: "def_lose.wav" },
      { word: "minute", korean: "n. 분", eng_def: "n. a unit of time equal to 60 seconds", example: "The bus will arrive in five minutes.", audio: "minute.wav", def_audio: "def_minute.wav" },
      { word: "nervous", korean: "a. 초조한, 긴장한", eng_def: "a. worried or frightened", example: "I was a little nervous on my first day at school.", audio: "nervous.wav", def_audio: "def_nervous.wav" },
      { word: "positive", korean: "a. 긍정적인", eng_def: "a. full of hope and confidence", example: "Happiness is a positive emotion.", audio: "positive.wav", def_audio: "def_positive.wav" },
      { word: "quit", korean: "v. 그만두다", eng_def: "v. to stop doing something", example: "He will quit his job this month.", audio: "quit.wav", def_audio: "def_quit.wav" },
      { word: "result", korean: "n. 결과", eng_def: "n. something that happens because of something else", example: "He was happy with his math test result.", audio: "result.wav", def_audio: "def_result.wav" },
      { word: "seat", korean: "n. 자리, 좌석", eng_def: "n. something you can sit on", example: "The window seat has a great view.", audio: "seat.wav", def_audio: "def_seat.wav" },
      { word: "situation", korean: "n. 상황", eng_def: "n. the conditions that exist at a particular time and place", example: "Can you explain the situation again?", audio: "situation.wav", def_audio: "def_situation.wav" },
      { word: "support", korean: "n. 지지, 응원 / v. 지지하다", eng_def: "n. emotional or practical help / v. to help and encourage someone, often when they are having problems", example: "I got a lot of support from Peter last week.", audio: "support.wav", def_audio: "def_support.wav" },
      { word: "surprised", korean: "a. 놀란", eng_def: "a. feeling or showing surprise because of something unexpected", example: "She was surprised at my gift.", audio: "surprised.wav", def_audio: "def_surprised.wav" },
      { word: "terrible", korean: "a. 끔찍한", eng_def: "a. very bad", example: "The traffic was terrible this morning.", audio: "terrible.wav", def_audio: "def_terrible.wav" },
      { word: "text", korean: "n. (문자) 메시지 / v. 메시지를 보내다", eng_def: "n. a text message / v. to send someone a written message using a cell phone", example: "I'm waiting for a text from my friend.", audio: "text.wav", def_audio: "def_text.wav" },
      { word: "throw", korean: "v. 던지다", eng_def: "v. to make something go through the air, by moving your arm", example: "I throw a ball, and my dog catches it.", audio: "throw.wav", def_audio: "def_throw.wav" },
      { word: "upset", korean: "a. 속상한, 마음이 상한", eng_def: "a. being unhappy and worried", example: "I felt upset because of my poor grades.", audio: "upset.wav", def_audio: "def_upset.wav" },
      { word: "waste", korean: "v. 낭비하다 / n. 쓰레기", eng_def: "v. to use more money, time, resources, etc. than is needed / n. things that are not wanted and get thrown away", example: "Don't waste your time on unimportant things.", audio: "waste.wav", def_audio: "def_waste.wav" }
    ]
  },
  {
    id: 4,
    title: "The Joy of Traveling",
    subtitle: "Lesson 4 - New Words",
    wordCount: 28,
    vocab: [
      { word: "amazing", korean: "a. 놀라운", eng_def: "a. very good in a surprising way", example: "The special effects in the movie were really amazing.", audio: "amazing.wav", def_audio: "def_amazing.wav" },
      { word: "amusement", korean: "n. 재미, 놀이", eng_def: "n. the feeling you have when you think something is funny", example: "The amusement park is open at night this week.", audio: "amusement.wav", def_audio: "def_amusement.wav" },
      { word: "be full of", korean: "~으로 가득 차다", eng_def: "to contain a lot of something", example: "The box was full of toys for children.", audio: "be_full_of.wav", def_audio: "def_be_full_of.wav" },
      { word: "bicycle", korean: "n. 자전거", eng_def: "n. a two-wheeled vehicle that you sit on and move by turning the two pedals", example: "She rides her bicycle to school every day.", audio: "bicycle.wav", def_audio: "def_bicycle.wav" },
      { word: "cliff", korean: "n. 절벽", eng_def: "n. a high area of rock with a very steep side", example: "The river went down the cliff and made a beautiful waterfall.", audio: "cliff.wav", def_audio: "def_cliff.wav" },
      { word: "explore", korean: "v. 탐험하다", eng_def: "v. to travel to a new place to learn about it", example: "We explored the narrow streets of the old town.", audio: "explore.wav", def_audio: "def_explore.wav" },
      { word: "fantastic", korean: "a. 환상적인", eng_def: "a. extremely good", example: "The weather was fantastic for a picnic.", audio: "fantastic.wav", def_audio: "def_fantastic.wav" },
      { word: "fee", korean: "n. 요금", eng_def: "n. an amount of money that you pay to do or use something", example: "There is no entrance fee to the zoo today.", audio: "fee.wav", def_audio: "def_fee.wav" },
      { word: "information", korean: "n. 정보", eng_def: "n. facts or details about something", example: "My friend shared helpful information about the test.", audio: "information.wav", def_audio: "def_information.wav" },
      { word: "island", korean: "n. 섬", eng_def: "n. a piece of land that is surrounded by water", example: "How many islands are there around Jeju-do?", audio: "island.wav", def_audio: "def_island.wav" },
      { word: "joy", korean: "n. 기쁨", eng_def: "n. great happiness", example: "The puppy jumped with joy at the smell of food.", audio: "joy.wav", def_audio: "def_joy.wav" },
      { word: "local", korean: "n. 주민, 현지인", eng_def: "n. a person who lives in a particular area, city, or town", example: "We asked a local for the way to the lake park.", audio: "local.wav", def_audio: "def_local.wav" },
      { word: "museum", korean: "n. 박물관", eng_def: "n. a place where interesting objects of art or historical items are displayed", example: "The museum has Picasso's paintings.", audio: "museum.wav", def_audio: "def_museum.wav" },
      { word: "narrow", korean: "a. 좁은", eng_def: "a. long and not wide; small from one side to the other side", example: "The road to the top of the mountain was narrow.", audio: "narrow.wav", def_audio: "def_narrow.wav" },
      { word: "on one's way to", korean: "…으로 가는 길에", eng_def: "in the process of coming, going, or traveling", example: "We are on our way to the store.", audio: "on_one_s_way_to.wav", def_audio: "def_on_one_s_way_to.wav" },
      { word: "order", korean: "v. 주문하다, 정리하다 / n. 순서", eng_def: "v. to ask for something in a restaurant; to put in order or to arrange something / n. the way that you arrange things", example: "Let's order a pizza for lunch.", audio: "order.wav", def_audio: "def_order.wav" },
      { word: "pearl", korean: "n. 진주", eng_def: "n. a hard, white, round object inside the shell of a sea creature and used to make jewelry", example: "In many cultures, a pearl means good luck.", audio: "pearl.wav", def_audio: "def_pearl.wav" },
      { word: "perfect", korean: "a. 완벽한", eng_def: "a. without any flaws or mistakes", example: "His answer to the question was perfect.", audio: "perfect.wav", def_audio: "def_perfect.wav" },
      { word: "rental", korean: "n. 대여", eng_def: "n. the act of paying for the use of something", example: "The bike rental costs $6 an hour.", audio: "rental.wav", def_audio: "def_rental.wav" },
      { word: "schedule", korean: "n. 일정, 스케줄", eng_def: "n. a plan, program, or timetable", example: "What's on your schedule for tonight?", audio: "schedule.wav", def_audio: "def_schedule.wav" },
      { word: "souvenir", korean: "n. 기념품", eng_def: "n. something you keep as a reminder of a special visit or event", example: "I bought a scarf as a souvenir of my trip to London.", audio: "souvenir.wav", def_audio: "def_souvenir.wav" },
      { word: "spend", korean: "v. (시간을) 보내다", eng_def: "v. to use time doing something or being somewhere", example: "My uncle spends his vacation traveling.", audio: "spend.wav", def_audio: "def_spend.wav" },
      { word: "terrace", korean: "n. 테라스", eng_def: "n. an open area, especially outside a house or restaurant, where you can sit and eat", example: "A small table and four chairs were on the terrace.", audio: "terrace.wav", def_audio: "def_terrace.wav" },
      { word: "tour", korean: "n. 여행", eng_def: "n. a visit to a place, especially to look around it and learn about it", example: "We joined a bus tour of the city.", audio: "tour.wav", def_audio: "def_tour.wav" },
      { word: "trail", korean: "n. 오솔길", eng_def: "n. a path through a countryside, mountain, or forest area", example: "We hike along the forest trail on weekends.", audio: "trail.wav", def_audio: "def_trail.wav" },
      { word: "vacation", korean: "n. 방학", eng_def: "n. a time away from work or school when you can relax", example: "During the vacation, we visited friends in another city.", audio: "vacation.wav", def_audio: "def_vacation.wav" },
      { word: "view", korean: "n. 경치", eng_def: "n. the things that you can see from a place", example: "The window in my room has a nice view of the garden.", audio: "view.wav", def_audio: "def_view.wav" },
      { word: "village", korean: "n. 마을", eng_def: "n. a very small town", example: "There are many colorful houses in the village.", audio: "village.wav", def_audio: "def_village.wav" }
    ]
  },
  {
    id: 5,
    title: "Think like Sherlock Holmes!",
    subtitle: "Lesson 5 - New Words",
    wordCount: 28,
    vocab: [
      { word: "bakery", korean: "n. 빵집", eng_def: "n. a place where bread and cakes are made or sold", example: "The bakery is famous for its cheesecakes.", audio: "bakery.wav", def_audio: "def_bakery.wav" },
      { word: "code", korean: "n. 암호", eng_def: "n. a set of letters, numbers, symbols, etc., that is used to secretly send messages to someone", example: "We unlocked a door with a special code.", audio: "code.wav", def_audio: "def_code.wav" },
      { word: "crime", korean: "n. 범죄", eng_def: "n. an action that the law does not allow", example: "Writing on walls can be a crime.", audio: "crime.wav", def_audio: "def_crime.wav" },
      { word: "criminal", korean: "n. 범죄자", eng_def: "n. a person who does something against the law, like stealing or hurting others", example: "The police caught the criminal this morning.", audio: "criminal.wav", def_audio: "def_criminal.wav" },
      { word: "damage", korean: "v. 손상을 입히다", eng_def: "v. to physically harm something", example: "The strong wind and heavy rain damaged the city.", audio: "damage.wav", def_audio: "def_damage.wav" },
      { word: "expensive", korean: "a. 비싼", eng_def: "a. costing a lot of money", example: "Those sneakers are too expensive for me.", audio: "expensive.wav", def_audio: "def_expensive.wav" },
      { word: "explain", korean: "v. 설명하다", eng_def: "v. to tell someone about something so that he or she can understand it", example: "The teacher explained the math problem to us.", audio: "explain.wav", def_audio: "def_explain.wav" },
      { word: "eyewitness", korean: "n. 목격자", eng_def: "n. someone who saw a crime or an accident", example: "We are looking for eyewitnesses of the accident.", audio: "eyewitness.wav", def_audio: "def_eyewitness.wav" },
      { word: "fall off", korean: "떨어지다", eng_def: "to drop to the ground from a high object", example: "He fell off the stairs and broke his leg.", audio: "fall_off.wav", def_audio: "def_fall_off.wav" },
      { word: "feed", korean: "v. 먹이를 주다", eng_def: "v. to give food to an animal", example: "Don't feed the fish in the pond.", audio: "feed.wav", def_audio: "def_feed.wav" },
      { word: "flash", korean: "n. 플래시 (촬영)", eng_def: "n. a bright light on a camera that you use when taking photographs inside a building", example: "I'll take a picture of you with the flash.", audio: "flash.wav", def_audio: "def_flash.wav" },
      { word: "guard", korean: "n. 경비원", eng_def: "n. a person whose job is to protect a person, place or thing from danger or attack", example: "There are guards at the entrance of the palace.", audio: "guard.wav", def_audio: "def_guard.wav" },
      { word: "height", korean: "n. 키", eng_def: "n. how tall someone or something is", example: "Yuna is the same height as me.", audio: "height.wav", def_audio: "def_height.wav" },
      { word: "janitor", korean: "n. 청소부, 관리인", eng_def: "n. a person in charge of cleaning and fixing things in a building", example: "The school janitor fixed the broken chair for me.", audio: "janitor.wav", def_audio: "def_janitor.wav" },
      { word: "language", korean: "n. 언어", eng_def: "n. the system of words and grammar that people living in a country or area use to speak and write to each other", example: "Lily can speak five languages.", audio: "language.wav", def_audio: "def_language.wav" },
      { word: "owner", korean: "n. 주인", eng_def: "n. someone who owns something", example: "Who is the owner of this laptop?", audio: "owner.wav", def_audio: "def_owner.wav" },
      { word: "pet", korean: "n. 반려동물", eng_def: "n. an animal that you keep at home", example: "Miley is a wonderful pet for my family.", audio: "pet.wav", def_audio: "def_pet.wav" },
      { word: "reason", korean: "n. 근거", eng_def: "n. something that makes it right or fair to do something", example: "Do you have any reasons for the choice?", audio: "reason.wav", def_audio: "def_reason.wav" },
      { word: "rule", korean: "n. 규칙", eng_def: "n. a statement of what you can or cannot do", example: "Being kind to everyone is our classroom rule.", audio: "rule.wav", def_audio: "def_rule.wav" },
      { word: "run away", korean: "도망치다", eng_def: "to leave a place or person secretly and suddenly", example: "My dog often runs away with my sock.", audio: "run_away.wav", def_audio: "def_run_away.wav" },
      { word: "scene", korean: "n. 현장, 장면", eng_def: "n. a place where something happens; a piece of a film or play, usually showing one situation", example: "The accident scene was near the bank.", audio: "scene.wav", def_audio: "def_scene.wav" },
      { word: "secret", korean: "a. 비밀의", eng_def: "a. not known or seen by others", example: "The chef shared a secret recipe with us.", audio: "secret.wav", def_audio: "def_secret.wav" },
      { word: "statement", korean: "n. 진술", eng_def: "n. something that you say or write officially", example: "Thanks to her statement, the police caught the criminal.", audio: "statement.wav", def_audio: "def_statement.wav" },
      { word: "steal", korean: "v. 훔치다", eng_def: "v. to take something that belongs to someone else", example: "A cat is trying to steal the fish from the plate.", audio: "steal.wav", def_audio: "def_steal.wav" },
      { word: "sunflower", korean: "n. 해바라기", eng_def: "n. a tall plant with a large yellow flower and a brown center", example: "The girl is putting a sunflower in her hair.", audio: "sunflower.wav", def_audio: "def_sunflower.wav" },
      { word: "suspect", korean: "n. 용의자", eng_def: "n. a person who is believed to be guilty of something", example: "The suspect has brown hair and blue eyes.", audio: "suspect.wav", def_audio: "def_suspect.wav" },
      { word: "wheelchair", korean: "n. 휠체어", eng_def: "n. a chair on wheels that people unable to walk use for moving around", example: "The building has wide doors for wheelchair users.", audio: "wheelchair.wav", def_audio: "def_wheelchair.wav" },
      { word: "wig", korean: "n. 가발", eng_def: "n. an object with hair on it that someone wears on their head", example: "We took a photo with colorful wigs.", audio: "wig.wav", def_audio: "def_wig.wav" }
    ]
  }
];
