const LESSONS = [
  {
    id: 1,
    title: "I Love Bands and Music",
    subtitle: "Lesson 1 - New Words",
    wordCount: 22,
    vocab: [
      { word: "all the time", korean: "내내, 아주 자주", eng_def: "at all times; continuously or very often", example: "He forgets his homework all the time.", audio: "all_the_time.wav", def_audio: "def_all_the_time.wav" },
      { word: "band", korean: "n. 밴드", eng_def: "a group of musicians who play music together", example: "Ben plays the guitar in a rock band.", audio: "band.wav", def_audio: "def_band.wav" },
      { word: "by one's side", korean: "좌우에, 옆에", eng_def: "close or beside someone", example: "She keeps a family photo by her side at work.", audio: "by_one_s_side.wav", def_audio: "def_by_one_s_side.wav" },
      { word: "each", korean: "a. 각각의", eng_def: "every one of two or more things or people", example: "The teacher always gives candies to each student.", audio: "each.wav", def_audio: "def_each.wav" },
      { word: "even", korean: "ad. ~도, 심지어", eng_def: "used to show that something is surprising", example: "He even goes to home with me.", audio: "even.wav", def_audio: "def_even.wav" },
      { word: "guide", korean: "n. 안내인", eng_def: "a person who shows the way and often gives information", example: "The guide leads us through the forest.", audio: "guide.wav", def_audio: "def_guide.wav" },
      { word: "gym", korean: "n. 체육관", eng_def: "a building or room that has equipment for doing physical exercises", example: "Tim goes to the gym every day.", audio: "gym.wav", def_audio: "def_gym.wav" },
      { word: "hearing", korean: "n. 청각", eng_def: "the ability to hear", example: "Loud music is not good for your hearing.", audio: "hearing.wav", def_audio: "def_hearing.wav" },
      { word: "keyboard", korean: "n. 키보드", eng_def: "a musical instrument with keys like a piano", example: "She carries her own keyboard for the concert.", audio: "keyboard.wav", def_audio: "def_keyboard.wav" },
      { word: "laugh", korean: "v. 웃다", eng_def: "to make a sound with your voice because you think something is funny", example: "She laughs at my funny story.", audio: "laugh.wav", def_audio: "def_laugh.wav" },
      { word: "magic", korean: "n. 마술", eng_def: "the use of tricks to entertain people", example: "My brother loves magic shows.", audio: "magic.wav", def_audio: "def_magic.wav" },
      { word: "match", korean: "v. 연결시키다", eng_def: "to put two things together in a suitable way", example: "Match the words with the pictures.", audio: "match.wav", def_audio: "def_match.wav" },
      { word: "memo", korean: "n. 메모", eng_def: "a usually brief written message from someone", example: "Mom leaves a daily memo for me.", audio: "memo.wav", def_audio: "def_memo.wav" },
      { word: "neighbor", korean: "n. 이웃", eng_def: "someone who lives near you", example: "My neighbor has two dogs.", audio: "neighbor.wav", def_audio: "def_neighbor.wav" },
      { word: "nod", korean: "v. 끄덕이다", eng_def: "to move the head down and then up again quickly", example: "He often nods his head along to music.", audio: "nod.wav", def_audio: "def_nod.wav" },
      { word: "person", korean: "n. 사람, 개인", eng_def: "a man, woman, or child", example: "The person with the hat is my cousin James.", audio: "person.wav", def_audio: "def_person.wav" },
      { word: "pop", korean: "a. 팝 (음악)의", eng_def: "of or relating to popular music", example: "I love pop songs a lot.", audio: "pop.wav", def_audio: "def_pop.wav" },
      { word: "practice", korean: "v. 연습하다 / n. 연습", eng_def: "to do something regularly so that you can do it better", example: "Grace practices the piano every day.", audio: "practice.wav", def_audio: "def_practice.wav" },
      { word: "special", korean: "a. 특별한", eng_def: "different from ordinary things and better in some way", example: "The restaurant has a special menu for children.", audio: "special.wav", def_audio: "def_special.wav" },
      { word: "subject", korean: "n. 과목", eng_def: "an area of knowledge or study, especially one that you study at school", example: "History is my favorite subject.", audio: "subject.wav", def_audio: "def_subject.wav" },
      { word: "tulip", korean: "n. 튤립", eng_def: "a large, bright flower that is shaped like a cup", example: "His garden is full of beautiful tulips.", audio: "tulip.wav", def_audio: "def_tulip.wav" },
      { word: "wide", korean: "a. 넓은", eng_def: "with a great distance from side to side; large", example: "There is a wide table in the kitchen.", audio: "wide.wav", def_audio: "def_wide.wav" }
    ]
  },
  {
    id: 2,
    title: "Healthy Food Fair",
    subtitle: "Lesson 2 - New Words",
    wordCount: 29,
    vocab: [
      { word: "bowl", korean: "n. 그릇", eng_def: "a round, deep dish used for food", example: "The bowl has some soup in it.", audio: "bowl.wav", def_audio: "def_bowl.wav" },
      { word: "chef", korean: "n. 요리사", eng_def: "a person who prepares food for people to eat; cook", example: "My uncle is a famous chef in my country.", audio: "chef.wav", def_audio: "def_chef.wav" },
      { word: "cherry tomato", korean: "n. 방울토마토", eng_def: "a type of very small tomato", example: "I like pasta with cherry tomatoes and basil leaves.", audio: "cherry_tomato.wav", def_audio: "def_cherry_tomato.wav" },
      { word: "different", korean: "a. 다른", eng_def: "not the same as something", example: "My brother and I like different kinds of music.", audio: "different.wav", def_audio: "def_different.wav" },
      { word: "enjoy", korean: "v. 즐기다", eng_def: "to like doing something", example: "He enjoys playing soccer with his friends.", audio: "enjoy.wav", def_audio: "def_enjoy.wav" },
      { word: "fair", korean: "n. 박람회", eng_def: "an event at which people show or sell things", example: "Many artists from different countries join the art fair.", audio: "fair.wav", def_audio: "def_fair.wav" },
      { word: "flour", korean: "n. 밀가루", eng_def: "a powder used for making bread and cakes", example: "You need flour, milk, and eggs for pancakes.", audio: "flour.wav", def_audio: "def_flour.wav" },
      { word: "fry", korean: "v. 튀기다", eng_def: "to cook food in hot oil", example: "We will fry some potatoes for dinner.", audio: "fry.wav", def_audio: "def_fry.wav" },
      { word: "garlic", korean: "n. 마늘", eng_def: "a small plant like an onion, used to give a strong taste to food", example: "This pasta uses only garlic and olive oil.", audio: "garlic.wav", def_audio: "def_garlic.wav" },
      { word: "healthy", korean: "a. 건강한", eng_def: "physically good and strong", example: "Regular exercise is a key to a healthy body.", audio: "healthy.wav", def_audio: "def_healthy.wav" },
      { word: "honey", korean: "n. 꿀", eng_def: "a sweet sticky, yellow substance made by bees", example: "Add honey for a tasty pizza.", audio: "honey.wav", def_audio: "def_honey.wav" },
      { word: "host", korean: "n. 진행자", eng_def: "a person who introduces guests and performers, especially on a television or radio show", example: "The host of the show has a great sense of humor.", audio: "host.wav", def_audio: "def_host.wav" },
      { word: "important", korean: "a. 중요한", eng_def: "having great meaning", example: "Regular exercise is important for your health.", audio: "important.wav", def_audio: "def_important.wav" },
      { word: "instead", korean: "ad. 대신에", eng_def: "in place of someone or something else", example: "I will wear a coat instead of a jacket today.", audio: "instead.wav", def_audio: "def_instead.wav" },
      { word: "jog", korean: "v. 조깅하다", eng_def: "to run at a slow steady speed for exercise", example: "Every morning, she jogs at the park.", audio: "jog.wav", def_audio: "def_jog.wav" },
      { word: "leaf", korean: "n. 잎", eng_def: "a flat and usually green part of a plant that grows out from a stem", example: "This is a leaf from that tree.", audio: "leaf.wav", def_audio: "def_leaf.wav" },
      { word: "nut", korean: "n. 견과류", eng_def: "a dry seed or fruit that has a hard shell", example: "Jenny enjoys a salad with a mix of nuts and vegetables.", audio: "nut.wav", def_audio: "def_nut.wav" },
      { word: "prize", korean: "n. 상", eng_def: "something given as a reward to the winner of a competition", example: "She always wins first prize in a speech contest.", audio: "prize.wav", def_audio: "def_prize.wav" },
      { word: "real", korean: "a. 진짜의", eng_def: "true, not fake or imaginary", example: "Is this ring real gold?", audio: "real.wav", def_audio: "def_real.wav" },
      { word: "regularly", korean: "ad. 규칙적으로", eng_def: "at the same time every day, week, month, etc. and usually often", example: "Maya regularly goes fishing with her dad.", audio: "regularly.wav", def_audio: "def_regularly.wav" },
      { word: "ride", korean: "v. 타다", eng_def: "to sit on a bicycle, motorcycle, or horse and make it move forward", example: "We will ride the train to the city.", audio: "ride.wav", def_audio: "def_ride.wav" },
      { word: "sentence", korean: "n. 문장", eng_def: "a group of words that makes a statement or asks a question", example: "Write a sentence about your favorite animal.", audio: "sentence.wav", def_audio: "def_sentence.wav" },
      { word: "skewer", korean: "n. 꼬치, 꼬챙이", eng_def: "a thin piece of wood or metal", example: "I want to eat chicken on skewers.", audio: "skewer.wav", def_audio: "def_skewer.wav" },
      { word: "soon", korean: "ad. 곧", eng_def: "in or within a short time; before long", example: "Dinner will be ready soon.", audio: "soon.wav", def_audio: "def_soon.wav" },
      { word: "teen", korean: "n. 10대 / a. 10대의", eng_def: "a young person between 13 and 19 years old", example: "Tony always carries his phone around, like most teens.", audio: "teen.wav", def_audio: "def_teen.wav" },
      { word: "thick", korean: "a. 걸쭉한", eng_def: "(of a liquid) not flowing easily", example: "The pasta sauce is thick and rich.", audio: "thick.wav", def_audio: "def_thick.wav" },
      { word: "topic", korean: "n. 주제", eng_def: "someone or something that people talk or write about", example: "You can choose a topic for your history project.", audio: "topic.wav", def_audio: "def_topic.wav" },
      { word: "trash", korean: "n. 쓰레기", eng_def: "things that you do not want and throw away", example: "He is throwing away the trash in the park.", audio: "trash.wav", def_audio: "def_trash.wav" },
      { word: "unhealthy", korean: "a. 건강하지 않은", eng_def: "not strong or well", example: "I won't eat unhealthy food like hamburgers often.", audio: "unhealthy.wav", def_audio: "def_unhealthy.wav" }
    ]
  }
];
